added crud car stations
IlyaTroshchynskyi/rent_cars_microservices pull request #3
Opened 2023-08-22 08:22 UTC by IlyaTroshchynskyi

2023-08-22 08:51 UTC, DenysMoskalenko requested changes

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +@router.get('/', response_model=list[CarStationReadCreate])
Уверен, что хочешь возвращать Create схему?

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +        return JSONResponse(content={'msg': 'Car station created'}, status_code=201)
Против ниче не имею, но чего ты в этом сервисе решил не возвращать созданный обьект? В других ведь возвращаешь...

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +from app.car_stations import schemas
Уже говорили про это

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/car_stations/schemas.py
> +settings = get_settings()
Почему ты решил создать глобальную переменную именно в этом файле?

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +    car_station.__dict__.update(data.model_dump(exclude_unset=True))
Менять внутрений дикт, но который полагается Pydantic мне не кажется лучшим решением.

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/app/redis_client.py
> +db_dependency = Annotated[redis.Redis, Depends(init_db)]
Ты каждый раз создаешь нового клиента и новый конекшн. При 50 одновременных запросов ты попытаешься создать 50 клиентов, перевалишь максимум TCP конекшинов и все будет очень сильно тормозить.
Да и в целом скорость работы будет такая себе.
Проблема кстати распространена, вот даже 2 недели назад я заметил такое у Лехи на проекте, они поменяли и общая производительность увеличилась где-то в 4 раза.

С постгрей ты же так не делаешь, ты создаешь клиента БД один раз, у него есть определенный пул конекшинов и с ним работаешь, чего тут решил иначе?

Я советую пойти другим путем, взять функцию get_redis_client, повесить на неё lru_cache и вызывать её. Т.е. сделаем хакнутый синглтон.

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/pyproject.toml
> +redis = {extras = ["hiredis"], version = "^5.0.0"}
Для чего тебе hiredis?

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
> +    await client.close()
Да это хороший подход, который сделаем тесты более надежными, так как Редис будет исопльзоваться настоящий в докере.
Но есть и другой подход, к котормоу иногда прибегают, когда время выполнения критично важно - мок бд в памяти.

Для редиса есть очень хорошая библиотека `fakeredis`, которая делает все за тебе, и тебе остается только прокинуть его в депенденси.
С подходом в докере ты хорошо знаком, давай попробуем теперь этот с `fakeredis`

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
> +async def car_stations(redis_client, car_station_factory) -> list[tuple[str, CarStationReadCreate]]:
тайпхинты потерял

2023-08-22 08:51 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
Какой процент покрытия получился?

2023-08-22 13:31 UTC, DenysMoskalenko requested changes

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +router = APIRouter(prefix='/car_station', tags=['Car Station'])
В url обычно не использут ни snake_case ни CamelCase, там разделяют слова дифисом, типо car-station

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +@router.post('/', response_model=CarStationCreate, status_code=201)
Так а зачем ты отдаешь Create ?)

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +@router.get('/', response_model=list[CarStationRead])
Я думаю сам домменный обьект можно не называть Read, а сократить до CarStation. Если ты хочешь поставить ударение, что это не доменный обьект а то, что уйдет как ответ, тогда это должно быть Response, Out и тд тп.

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/car_stations/schemas.py
> +    for hour in value.split('-'):
```
a = '12:00'
a.split('-')
```
Ошибки не будет, но данные не валидны

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +    return await db.delete(station_id)
Исходя из применений этой функции ты ожидаешь "правдивое" или "ложное" значение is_deleted. Мне кажется будет лучше отдавать более понятный bool, а не тянуть 0 и 1, как ответы из редиса.

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +async def update_car_station(db: Redis, station_id: str, data: CarStationUpdate) -> CarStationUpdate | None:
Вот подобные CarStationUpdate | None начинают появляться, когда идешь по этому пути. Окей, если это используется в нескольких местах, но представь, что эта функция может вызываться в других 10, и каждый раз тебе нужно проверять, что пришел не None и чет с этим делать.
А если такая функция вложена в другую, та тоже возвращает None и опять и опять.

Мне больше нравится подход вызывания кастомных ошибок, по типу NotFound. Так в местах где ты ожидаешь, что что-то может не найтись ты сможешь её обработать, это будет ничем не сложнее, чем проверка if station: ... Но очень поможет в случаях, которые я описал

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +    await db.set(station_id, json.dumps(dict_car_station))
Просто для инфы, если намного лучше либы для сериализации и парсинга жсона, например orjson, которая на расте и во много раз быстрее стандартной.
FastAPI lаже поддерживает ORJSONResponse и UJSONResponse, правда это стало не очень актуальным со второй версии пайдентика, который тоже на расте

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +    car_station_str = await retrieve_car_station(db, station_id)
Почему retrieve_car_station должно возвращать строку? Почему не десериализовывать это в словарь прям там? Опять-же не давай логике хранилища влиять на логику приложения. У тебя есть функция "получить станцию", ты ожидаешь, что получишь какой-то обьект станции, а не строку непонятной структуры, которую плиз распарси и тд тп.

Мне нравится вариант, когда аперируют доменной моделью CarStation это удобно и просто. Но это не совсем подходит под DAO, ведь DAO должно оперировать моделью БД, а просить тебя делать 2 одинаковые модели не хочется. (по этому я б просто переименовал dao в service или чет такое

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +    dict_car_station.update(data.model_dump(exclude_unset=True))
CarStationCreate ты используешь для обновления, давай сделаем Update, даже если она полностью повторяет криейд, тогда унаследуй.

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/dao/car_station.py
> +async def update_car_station(db: Redis, station_id: str, data: CarStationUpdate) -> CarStationUpdate | None:
data - самое ужасное названия для чего либо, такого быть не должно

2023-08-22 13:31 UTC, DenysMoskalenko commented on geo_service/app/redis_client.py
> +    await client.close()
Я не думаю что эта функция тебе нужна вообще.
+ я не думаю, что тебе нужно закрывать клиента, ты ведь им пользуешься все приложение. Закрытие можно постаить на шотдаун ивент разве-что.

2023-08-22 14:25 UTC, IlyaTroshchynskyi commented on geo_service/app/dao/car_station.py
> +    await db.set(station_id, json.dumps(dict_car_station))
Да тоже заметил что они там убрали параметр в конфиге для ORJSONResponse

2023-08-22 15:01 UTC, IlyaTroshchynskyi commented on geo_service/app/dao/car_station.py
> +    dict_car_station.update(data.model_dump(exclude_unset=True))
обновилось по другому

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/app/car_stations/router.py
> +        raise HTTPException(status_code=404, detail='Car station not found')
1) В других местах ты все=же поменял на NotFoundError, чего тут нет? Как по мне должно быть одинаково везде, либо так либо так

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/app/car_stations/schemas.py
> +class CarStationIn(BaseModel):
Просто мнение: Create название мне нравилось больше чем IN, Но это твое решение)

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/app/car_stations/schemas.py
> +        return _validate_format(value)
Не обязательно заново это все писать, ты можешь унаследовать одну модель от другой, в данном случае я вижу, что Create расширяет эту.
Но на самом деле в таком разделении есть тоже и плюсы и минусы

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/app/car_stations/schemas.py
> +    raise ValueError('Must be such format %H:%M')
Наверное тогда чет типо "H:M-H:M" ?

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
> +    yield get_client_redis()
Не совсем понимаю зачем это

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
> +    __random_seed__ = 1
а что будет, если это не задавать?

2023-08-23 07:08 UTC, DenysMoskalenko commented on geo_service/tests/conftest.py
> +    __model__ = CarStationIn
А точно нужно в 2-х местах задавать CarStationIn? Не хватит в одном?

2023-08-23 08:01 UTC, merged