added crud reviews
IlyaTroshchynskyi/rent_cars_microservices pull request #4
Opened 2023-08-23 14:47 UTC by IlyaTroshchynskyi

2023-08-23 15:59 UTC, DenysMoskalenko requested changes

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/cars/router.py
> +        await delete_car_image(settings.STATIC_DIR + filename)
А ты не думал инкапсулировать delete_car_image в функцию delete_car?
Разве есть явный флоу, когда ты хочешь удалить машину. но картинку оставить?

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/cars/router.py
> +        await delete_car_image(settings.STATIC_DIR + filename)
try/except блок должен покрывать только то, что нужно. Т.е. в функции delete_car_image у тебя никогда не будет NotFoundError, значит эта функция не должна быть под этим блоком. (Но этот комент возможно станет не актуальным, после инкапсуляции)

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/dao/car.py
> +from app.cars.schemas import CarUpdate
Выбери один из вариантов

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/dao/reviews.py
> +        .returning(Review)
Чтоб не ставить ужасные \ можно делать так:
```
query = (
    update(Review)
    .filter(Review.id == review.id)
    ...
)
```

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/dao/reviews.py
> +async def _retrieve_review(db: AsyncSession, review_id: int) -> Review:
А почему это приватный метод, нет кейса, когда нужно получить ревью по айди?

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/migrations/versions/a5ba43ea6681_create_models.py
> +                    sa.Column('parent_id', sa.Integer(), nullable=True),
На учебном проекте ок. Когда ты 1 разработчик, иногда тоже ок. Я б тоже сделал так-же для простоты
Но на прод проекте такое делать нельзя.

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/app/reviews/router.py
> +async def get(db: db_dependency):
название функции идет как описание в свагер, по этому лучше сделать её более полной, чем просто get, create и тд

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/pyproject.toml
> +psycopg2-binary = "^2.9.7"
На самом деле, проблема почему у тебя не работает psycopg2, который не binary заключается в том, что у тебя чего-то по питону не хватает. Она решается. И если ты попробуешь собрать в докере с обычным psycopg2 - у тебя не будет никаких проблем.

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/pyproject.toml
> +psycopg2-binary = "^2.9.7"
Более важный момент, что ты испоьзуешь вторую алхимию, которая поддерживает асинхронный и мощный psycopg3 и топит за его использование. ПО этому причину брать asyncpg я не вижу

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/tests/utils.py
такие названия файлов как utils, helpers и тд должны быть для тебя красным флагом. Это значит что что-то в построении проекта не так и ты не можешь придумать куда засунуть этот кусочек и складываешь их в муссорку utils, которая со временем разростается ппц.
Прото поставь себе как правило никогда такого не делать, и тогда ты начнешь думать, а че ж мне с этой функцией сделать если она никуда не притыкивается. И вот эти размышления будут тебе очень полезны

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/tests/test_reviews.py
> +    input_dict.update({'car_id': car.id})
Как вариант, можно ещё сделать чет такое:
`input = {** review_1.model_dump(exclude={'car_id', 'parent_id'}), 'car_id': car.id}`
Либо такое:
`input = review_1.model_dump(exclude={'car_id', 'parent_id'}) | {'car_id': car.id}`

2023-08-23 15:59 UTC, DenysMoskalenko commented on cars_service/tests/test_reviews.py
> +    input_dict.update({'car_id': car.id})
Очень советуется не исопльзовать типы данных в названии. Т.е. list, dict и тд - это плохой тон нейминга

2023-08-28 08:24 UTC, IlyaTroshchynskyi commented on cars_service/app/dao/reviews.py
> +async def _retrieve_review(db: AsyncSession, review_id: int) -> Review:
да такого кейса нет

2023-08-28 08:50 UTC, DenysMoskalenko requested changes

2023-08-28 08:50 UTC, DenysMoskalenko commented on cars_service/app/cars/router.py
> +async def update_image_for_car(car_id: int, file: UploadFile, db: db_dependency):
Поечму это отдельный эндпоинт? У тебя ж уже есть обновление для этой сущности.
Такого быть не должно

2023-08-28 08:50 UTC, DenysMoskalenko commented on cars_service/app/dao/reviews.py
> +async def _retrieve_review(db: AsyncSession, review_id: int) -> Review:
чего?)

2023-08-28 08:50 UTC, DenysMoskalenko commented on cars_service/pyproject.toml
> +aiofiles = "^23.2.1"
*Просто интересно*
Ты разбирался как оно работает? (Работа с файлами не бывает асинхронной)

2023-08-28 08:50 UTC, DenysMoskalenko commented on cars_service/tests/dao_test.py
Что ты имел ввиду под "dao_test" ?

2023-08-28 15:37 UTC, DenysMoskalenko approved these changes
Норм

2023-08-28 15:37 UTC, DenysMoskalenko commented on cars_service/app/cars/schemas.py
> +        return json.loads(data) if isinstance(data, str) else data
А это зачем?

2023-08-28 15:37 UTC, DenysMoskalenko commented on cars_service/tests/test_reviews.py
> +    assert response_data[0]['sub_reviews'][0]['parent_id'] == review_db_2.parent_id
Мне комфортнее делать чет типо:
`sub-review = response_data[0]['sub_reviews'][0]` и работать уже с этой переменной, но подходы разные)

2023-08-28 16:02 UTC, merged